name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: 'arnwaaa-web3'
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
